AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/omniauth/strategy_france_connect_spec.rb
    - lib/omniauth/france_connect.rb

Metrics/AbcSize:
  Exclude:
    - lib/omniauth/france_connect.rb

